// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vduswitch.cpp"
#include "Vduswitch___024root__DepSet_he81a9731__0.cpp"
#include "Vduswitch___024root__DepSet_h2b000e93__0.cpp"
#include "Vduswitch__Trace__0.cpp"
#include "Vduswitch___024root__Slow.cpp"
#include "Vduswitch___024root__DepSet_he81a9731__0__Slow.cpp"
#include "Vduswitch___024root__DepSet_h2b000e93__0__Slow.cpp"
#include "Vduswitch__Syms.cpp"
#include "Vduswitch__Trace__0__Slow.cpp"
